const { verifyUserMail, registerRole, userProfile, sendPasswdResetLink, resetPassword } = require("./auth.controller");
const { vendorProfile, uploadCatImage, createUpdateVendor, propertyRooms, switchRoomState, deleteRoom, bookRoom, bookingHistory, vendorDashboard, pricingList, activityList, uploadActivityImage, uploadPropertyImage, uploadPropertyDoc, propertyImagesList, updateSingleRoom, deletePropertyImage, propertyDocsList, deletePropertyDoc, uploadAmenityImage, getAmenities, getAmenitiesWholeData } = require("./vendor.controller");
const { featureController, adminDashboard, adminTodoList, propertyList, propertyFinanceLegal, vendorList, bookingList, commissionList, blogController, uploadBlogImage, couponController, getbookinglist } = require("./admin.controller.js");
const { userPropertyController, uploadProfilePic, getProfilePic,getRoomDetails,getPropertyDetails, getRoomCategories, userCategoryController,getRoomcategoriesByLocation, getUserCoupon, getSimilarroom, getRoomGroupCard, Join_Our_Community, getThought, uploadThoughtImage, getBloger, createFaq, getBlogLimit, blogCommentForm, getBlogComment, createAboutus, getAboutus, UserReview, getUserReview, getTouchWithUs, getTouchWith, updateTouchWithUs, updateAboutUs, getBlogerdetails, faqQuestions, getAmenitiesWithTravelMood } = require("./user.controller");
const { propertyReviewController } = require("./review.controller");
const { getNotifications, updateNotifications } = require("./notification.controller");
const { registerCustomer, verifyOtp, updateCustumer, getcustomers } = require("./customer.controller");
const { getbooking, createbooking,updatebooking, getBookingByUserId, getbookbycat } = require("./booking.controller");
const { contactDetails } = require("./contact.controller");

module.exports = {
  activityList,
  registerRole,
  vendorProfile,
  createUpdateVendor,
  propertyRooms,
  switchRoomState,
  bookRoom,
  bookingHistory,
  vendorDashboard,
  userProfile,
  pricingList,
  uploadActivityImage,
  verifyUserMail,
  deleteRoom,
  uploadPropertyImage,
  uploadPropertyDoc,
  adminDashboard,
  adminTodoList,
  propertyImagesList,
  updateSingleRoom,
  deletePropertyImage,
  propertyList,
  propertyFinanceLegal,
  vendorList,
  bookingList,
  commissionList,
  blogController,
  uploadBlogImage,
  featureController,
  couponController,
  userPropertyController,
  propertyReviewController,
  propertyDocsList,
  deletePropertyDoc,
  getNotifications,
  updateNotifications,
  uploadProfilePic,
  getProfilePic,
  sendPasswdResetLink,
  resetPassword,
  getRoomDetails,
  getPropertyDetails,
  registerCustomer,
  verifyOtp,
  getRoomCategories,
  getbooking,
  createbooking,
  updateCustumer,
  updatebooking,
  getBookingByUserId,
  contactDetails,
  userCategoryController,
  getRoomcategoriesByLocation,
  getbookinglist,
  getbookbycat,
  uploadAmenityImage,
  getAmenities,
  getAmenitiesWholeData,
  uploadCatImage,
  getUserCoupon,
  getSimilarroom,
  getRoomGroupCard,
  Join_Our_Community,
  getThought,
  uploadThoughtImage,
  getcustomers,
  getBloger,
  createFaq,
  faqQuestions,
  getBlogLimit,
  blogCommentForm,
  getBlogComment,
  createAboutus,
  getAboutus,
  UserReview,
  getUserReview,
  getTouchWithUs,
  getTouchWith,
  updateTouchWithUs,
  updateAboutUs,
  getBlogerdetails,
  getAmenitiesWithTravelMood
};





// const { verifyUserMail, registerRole, userProfile, sendPasswdResetLink, resetPassword } = require("./auth.controller");
// const { vendorProfile, createUpdateVendor, propertyRooms, switchRoomState, deleteRoom, bookRoom, bookingHistory, vendorDashboard, pricingList, activityList, uploadActivityImage, uploadPropertyImage, uploadPropertyDoc, propertyImagesList, updateSingleRoom, deletePropertyImage, propertyDocsList, deletePropertyDoc } = require("./vendor.controller");
// const { featureController, adminDashboard, adminTodoList, propertyList, propertyFinanceLegal, vendorList, bookingList, commissionList, blogController, uploadBlogImage, couponController } = require("./admin.controller.js");
// const { userPropertyController, uploadProfilePic, getProfilePic,getRoomDetails,getPropertyDetails, getRoomCategories, userCategoryController } = require("./user.controller");
// const { propertyReviewController } = require("./review.controller");
// const { getNotifications, updateNotifications } = require("./notification.controller");
// const { registerCustomer,verifyOtp, updateCustumer } = require("./customer.controller");
// const { getbooking, createbooking, updatebooking, getBookingByUserId } = require("./booking.controller");
// const { contactDetails } = require("./contact.controller");

// module.exports = {
//   activityList,
//   registerRole,
//   vendorProfile,
//   createUpdateVendor,
//   propertyRooms,
//   switchRoomState,
//   bookRoom,
//   bookingHistory,
//   vendorDashboard,
//   userProfile,
//   pricingList,
//   uploadActivityImage,
//   verifyUserMail,
//   deleteRoom,
//   uploadPropertyImage,
//   uploadPropertyDoc,
//   adminDashboard,
//   adminTodoList,
//   propertyImagesList,
//   updateSingleRoom,
//   deletePropertyImage,
//   propertyList,
//   propertyFinanceLegal,
//   vendorList,
//   bookingList,
//   commissionList,
//   blogController,
//   uploadBlogImage,
//   featureController,
//   couponController,
//   userPropertyController,
//   propertyReviewController,
//   propertyDocsList,
//   deletePropertyDoc,
//   getNotifications,
//   updateNotifications,
//   uploadProfilePic,
//   getProfilePic,
//   sendPasswdResetLink,
//   resetPassword,
//   getRoomDetails,
//   getPropertyDetails,
//   registerCustomer,
//   verifyOtp,
//   getRoomCategories,
//   getbooking,
//   createbooking,
//   updateCustumer,
//   updatebooking,
//   getBookingByUserId,
//   contactDetails,
//   userCategoryController,
// };
