const { getUserById, sendVerificationMail, otpGeneration, insertUpdateVendorProfileInfo, sendPasswdResetMail, getsimilar } = require("./user.service");
const { getVendorProfileInfo, getVendorList } = require("./vendor.service");
const { getPropertyNames, createProperty, getPropertyByVendorId, updateProperty, getActivityByPropertyId, insertUpdateVendorActivity, getPropertyImages, getPropertyList, getPropertyFinanceLegal, updatePropertyStatus, getPropertyForUserWithFilters,getMostPopularProperty, getLocation, getPropertyDocs, getRoomPropertyDetails,getRoomCategoryDetailsService , getRoomCategoryDetails, getRoomCatCard, getRoomCatGroupCard  } = require("./property.service");
const { deleteFeatured, addToFeaturedList, getCategoryNames, createCategory, updateCategory, createRoom, getRoomsByPropertyId, updateRoomStatus, getAllRooms, getAllCategories, insertUpdatePricingList, getPricingListByPropertyId, getRoomsForUser, category } = require("./room.service");
const { insertBookingNew, getBookingInfoByBookingId, doBooking, getBookingListByVendorId, getDashboardInfo, getBookingList, getbookingbyuserInfo, getbookingbybook } = require("./booking.service");
const { updateFeatured, getFeaturedList, getAdminDashboardInfo, insertAdminTodo, getAdminTodoList, updateAdminTodo, deleteAdminTodo, getPricingAndTaxCommission, updatePricingAndTaxCommission, deletePricingAndTaxCommission, insertBlog, getBlog, updateBlog, deleteBlog, createPricingAndTaxCommission } = require("./admin.service");
const { getCoupons, createCoupon, updateCoupon, deleteCoupon, getuserCoupons } = require("./coupon.service");
const { insertReview, getReviewsByPropertyId, updateReview, deleteReview, updateReviewReply } = require("./review.service");

module.exports = {
  getPropertyForUserWithFilters,
  getMostPopularProperty,
  createPricingAndTaxCommission,
  updatePropertyStatus,
  addToFeaturedList,
  getCategoryNames,
  getPropertyNames,
  updateFeatured,
  getVendorProfileInfo,
  createProperty,
  getPropertyByVendorId,
  updateProperty,
  createCategory,
  updateCategory,
  createRoom,
  getAllRooms,
  getAllCategories,
  getRoomsByPropertyId,
  getBookingInfoByBookingId,
  updateRoomStatus,
  doBooking,
  getBookingListByVendorId,
  getDashboardInfo,
  getUserById,
  insertUpdatePricingList,
  getPricingListByPropertyId,
  getActivityByPropertyId,
  insertUpdateVendorActivity,
  sendVerificationMail,
  otpGeneration,
  getAdminDashboardInfo,
  insertAdminTodo,
  insertUpdateVendorProfileInfo,
  getPropertyImages,
  getAdminTodoList,
  updateAdminTodo,
  deleteAdminTodo,
  getPropertyList,
  getPropertyFinanceLegal,
  getVendorList,
  getBookingList,
  getPricingAndTaxCommission,
  updatePricingAndTaxCommission,
  deletePricingAndTaxCommission,
  insertBlog,
  getBlog,
  updateBlog,
  deleteBlog,
  insertBookingNew,
  getFeaturedList,
  deleteFeatured,
  getCoupons,
  createCoupon,
  updateCoupon,
  deleteCoupon,
  insertReview,
  getReviewsByPropertyId,
  updateReview,
  deleteReview,
  updateReviewReply,
  getLocation,
  getRoomsForUser,
  getPropertyDocs,
  sendPasswdResetMail,
  getRoomPropertyDetails,
  // getPropertyDetailsService,
  getRoomCategoryDetails,
  category,
  getRoomCatCard,
  getbookingbyuserInfo,
  getbookingbybook,
  getuserCoupons,
  getsimilar,
  getRoomCatGroupCard,
};




